### ISSUE TITLE
API server issue

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/iso-api#1]
There has been something odd happening to the API server. It sometimes stops because it appears that someone has stopped it, thus stopping other apps like the Pandora-IsoMemo Webapp. It doesn't appear to be INWT's side, but perhaps someone in the MPI infrastructure is using the server to run other tasks and as a result, the IsoMemo API server is interrupted. 

Please update as you see fit @wahani

**Comment by wahani** [comment]
After more than 3 years without any incident we now have the API being stopped. As far as I can tell the docker daemon is stopped. Maybe because of a system reboot, or due to an explicit stop via `systemctl`.  I have changed the restart policy from `unless-stopped` to `always` for the service. This may resolve the issue. Documentation can be found here: https://docs.docker.com/config/containers/start-containers-automatically/

**Comment by jroachell15** [comment]
@isomemo Ricardo, The comment above pertains to your questions to the Server issues. As you mentioned, if the MPI IT team allocated Isomemo Apps its own server space, could this also possibly solve this API disconnection issue? @wahani 
- This `systemctl` and turning policy to `always` for the service, do we do this on our end or do we need MPI IT team to commit this?

**Comment by wahani** [comment]
> This systemctl and turning policy to always for the service, do we do this on our end or do we need MPI IT team to commit this?

It's our responsibility and already active.

**Comment by wahani** [comment]
Same issue just occured again. A restart seems to resolve it.

**Comment by wahani** [comment]
We have not had any issues with this in the past weeks. I assume the changes have resolved our problems.
